# Generated by Django 2.2.5 on 2019-09-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='studentformsave',
        ),
    ]
